### ISSUE TITLE
test

### ISSUE THREAD

**Issue by jesomekh** [jesomekh/Test#3]

**Comment by jesomekh** [comment]
test

**Comment by jesomekh** [comment]
test

**Comment by jesomekh** [comment]
test

**Comment by labrose** [comment]
@jesomekh can you assign and then unassign again? I subscribed to check out what the notifications do.

**Comment by jesomekh** [comment]
@labrose done :)

**Comment by labrose** [comment]
Interesting. Only got an email for your comment. What if you just assign it to yourself (don't conflict the change)?

**Comment by labrose** [comment]
![image](https://user-images.githubusercontent.com/22751162/40798829-d88ed662-64c0-11e8-8f84-96c19d3c7fc4.png)

**Comment by labrose** [comment]
GitLab lets you select, but again you only get comment notifications and potentially assignment changes depending on settings.

![image](https://user-images.githubusercontent.com/22751162/40799056-6bbeb326-64c1-11e8-8360-c042e67f0240.png)
